# Generated by Django 5.2.3 on 2025-06-18 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Cuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número del cuarto')),
                ('piso', models.IntegerField(verbose_name='Piso')),
                ('capacidad', models.PositiveIntegerField(default=1, verbose_name='Capacidad de personas')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del cuarto')),
                ('servicios', models.TextField(blank=True, help_text='Ej: WiFi, TV, Aire acondicionado', null=True, verbose_name='Servicios incluidos (separados por comas)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_cuartos/', verbose_name='Imagen del cuarto')),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por noche')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.categoriacuarto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Cuarto',
                'verbose_name_plural': 'Cuartos',
                'ordering': ['piso', 'numero'],
            },
        ),
    ]
