# Generated by Django 5.2.3 on 2025-06-19 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Cuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número del cuarto')),
                ('piso', models.IntegerField(verbose_name='Piso')),
                ('capacidad', models.PositiveIntegerField(default=1, verbose_name='Capacidad de personas')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del cuarto')),
                ('servicios', models.TextField(blank=True, help_text='Ej: WiFi, TV, Aire acondicionado', null=True, verbose_name='Servicios incluidos (separados por comas)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_cuartos/', verbose_name='Imagen del cuarto')),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por noche')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.categoriacuarto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Cuarto',
                'verbose_name_plural': 'Cuartos',
                'ordering': ['piso', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ReservaCuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Código de Reserva')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('documento_cliente', models.CharField(max_length=20, verbose_name='Documento del cliente')),
                ('correo_cliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del cliente')),
                ('telefono_cliente', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono del cliente')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('fecha_reserva', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de reserva')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('ocupado', 'Ocupado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='reservado', max_length=10, verbose_name='Estado de la reserva')),
                ('cuarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.cuarto', verbose_name='Cuarto reservado')),
            ],
            options={
                'verbose_name': 'Reserva de Cuarto',
                'verbose_name_plural': 'Reservas de Cuartos',
                'ordering': ['-fecha_reserva'],
            },
        ),
    ]
