# Generated by Django 5.2.3 on 2025-06-18 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaCuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('dni_cliente', models.CharField(max_length=20, verbose_name='DNI del cliente')),
                ('correo_cliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('telefono_cliente', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la reserva')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones del cliente')),
                ('cuarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.cuarto', verbose_name='Cuarto reservado')),
            ],
            options={
                'verbose_name': 'Reserva de Cuarto',
                'verbose_name_plural': 'Reservas de Cuartos',
                'ordering': ['-fecha_reserva'],
            },
        ),
    ]
