# Generated by Django 5.2.3 on 2025-07-02 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_roomreservation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_general', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', max_length=100, verbose_name='Estado General del Cuarto')),
                ('observaciones_piso', models.TextField(blank=True, null=True, verbose_name='Observaciones del Piso')),
                ('observaciones_paredes', models.TextField(blank=True, null=True, verbose_name='Observaciones de las Paredes')),
                ('observaciones_muebles', models.TextField(blank=True, null=True, verbose_name='Observaciones de Mobiliario')),
                ('observaciones_servicios', models.TextField(blank=True, null=True, verbose_name='Servicios (TV, agua, luz, etc.)')),
                ('limpieza_general', models.TextField(blank=True, null=True, verbose_name='Observaciones de Limpieza')),
                ('otros_detalles', models.TextField(blank=True, null=True, verbose_name='Otros Detalles')),
                ('evidencia_1', models.ImageField(blank=True, null=True, upload_to='room_inspections/', verbose_name='Evidencia 1')),
                ('evidencia_2', models.ImageField(blank=True, null=True, upload_to='room_inspections/', verbose_name='Evidencia 2')),
                ('evidencia_3', models.ImageField(blank=True, null=True, upload_to='room_inspections/', verbose_name='Evidencia 3')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Reporte')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.roomcategory', verbose_name='Categoría del Cuarto')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='libreria.roomreservation', verbose_name='Reserva Asociada')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.room', verbose_name='Cuarto Inspeccionado')),
            ],
            options={
                'verbose_name': 'Informe de Inspección del Cuarto',
                'verbose_name_plural': 'Informes de Inspección de Cuartos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
